// AUTO-GERADO por scripts/import-squads.js — NÃO EDITE MANUALMENTE
// Fonte: 2026_Dados_Cadastrais_Base.xlsx
// Para atualizar: npm run import-squads

export const POSITIONS = [
  "Goleiro","Zagueiro","Lateral Direito","Lateral Esquerdo",
  "Volante","Meia","Ponta","Atacante",
];

export const CAT_LIST = [
  "Sub 07","Sub 08","Sub 09","Sub 10","Sub 11","Sub 12","Sub 13","Sub 14","Sub 15","Sub 16","Sub 17","Sub 20","Profissional","Feminino",
];

export const BASE_CATS = CAT_LIST.filter(c => c.startsWith("Sub"));

export const SQUADS = {
  "Sub 07": [
    {id:1,athleteId:"AndryXavier2019",name:"ANDRY XAVIER DE MELLO",nickname:"Andry Xavier",number:"",pos:"Atacante",photo:""},
    {id:2,athleteId:"ArthurGabryel2019",name:"ARTHUR GABRYEL DA CUNHA RODRIGUES",nickname:"Arthur Gabryel",number:"",pos:"Atacante",photo:""},
    {id:3,athleteId:"ArthurCosta2019",name:"ARTHUR SIQUEIRA DA COSTA",nickname:"Arthur Costa",number:"",pos:"Ponta",photo:""},
    {id:4,athleteId:"AthilaPinto2019",name:"ATHILA BERNARDO BRAGA DA SILVA PINTO",nickname:"Athila Bernardo",number:"",pos:"Volante",photo:""},
    {id:5,athleteId:"AugustoCarvalho2019",name:"AUGUSTO LIBÓRIO CARVALHO",nickname:"Augusto Libório",number:"",pos:"Ponta",photo:""},
    {id:6,athleteId:"BenjaminSilva2019",name:"BENJAMIN PEREIRA DA SILVA",nickname:"Benjamin Pereira",number:"",pos:"Volante",photo:""},
    {id:7,athleteId:"BenjaminSantos2019",name:"BENJAMIN VIANNA DOS SANTOS",nickname:"Benjamin dos Santos",number:"",pos:"Volante",photo:""},
    {id:8,athleteId:"BernardoCardoso2019",name:"BERNARDO CORRÊA CARDOSO",nickname:"Bernardo",number:"",pos:"Volante",photo:""},
    {id:9,athleteId:"DaviRamalho2019",name:"DAVI BARBOSA RAMALHO",nickname:"Davi Ramalho",number:"",pos:"Atacante",photo:""},
    {id:10,athleteId:"DaviSantos2019",name:"DAVI BEZERRA SANTOS",nickname:"Davi Santos",number:"",pos:"Atacante",photo:""},
    {id:11,athleteId:"DaviPena2019",name:"DAVI PENA FAZA DE SOUZA",nickname:"Davi Pena",number:"",pos:"Ponta",photo:""},
    {id:12,athleteId:"DominickCesar2019",name:"DOMINICK CESAR DUQUE DA SILVA",nickname:"Dominick",number:"",pos:"Goleiro",photo:""},
    {id:13,athleteId:"EduardoLarsen2019",name:"EDUARDO LARSEN DE ALMEIDA",nickname:"Eduardo Larsen",number:"",pos:"Ponta",photo:""},
    {id:14,athleteId:"GuilhermeCardoso2019",name:"GUILHERME CORRÊA CARDOSO",nickname:"Guilherme Cardoso",number:"",pos:"Goleiro",photo:""},
    {id:15,athleteId:"GuilhermeViegas2019",name:"GUILHERME VIEGAS",nickname:"Guilherme Viegas",number:"",pos:"Volante",photo:""},
    {id:16,athleteId:"JoaoJunqueira2019",name:"JOÃO FELIPE GUIMARÃES JUNQUEIRA",nickname:"João Junqueira",number:"",pos:"Ponta",photo:""},
    {id:17,athleteId:"JoaoFrizero2019",name:"JOÃO VITOR COUTO FRIZERO",nickname:"João Frizero",number:"",pos:"Volante",photo:""},
    {id:18,athleteId:"JuanGaldino2019",name:"JUAN BRITO TORRES GALDINO",nickname:"Juan Galdino",number:"",pos:"Volante",photo:""},
    {id:19,athleteId:"LucasMateus2019",name:"LUCAS MATEUS NUNES NÓBREGA",nickname:"Lucas Mateus",number:"",pos:"Ponta",photo:""},
    {id:20,athleteId:"PedroMartins2019",name:"PEDRO MACIEL MARTINS",nickname:"Pedro Maciel",number:"",pos:"Zagueiro",photo:""},
    {id:21,athleteId:"PietroBatista2019",name:"PIETRO MELLO BATISTA",nickname:"Pietro Batista",number:"",pos:"Meia",photo:""},
    {id:22,athleteId:"RianRomeu2019",name:"RIAN NEUBAUER DO NATAL ROMEU",nickname:"Rian Romeu",number:"",pos:"Goleiro",photo:""},
    {id:23,athleteId:"VicenteRocha2019",name:"VICENTE COSTA DA ROCHA",nickname:"Vicente Costa",number:"",pos:"Meia",photo:""},
  ],
  "Sub 08": [
    {id:1,athleteId:"AdryanPacheco2018",name:"Adryan do Carmo Pacheco da Silva",nickname:"Adrian Pacheco",number:"",pos:"Volante",photo:""},
    {id:2,athleteId:"ArthurBrandao2018",name:"Arhur Brandão Mazzei de Oliveira",nickname:"Arthur Brandão",number:"",pos:"Volante",photo:""},
    {id:3,athleteId:"CaioCosta2018",name:"Caio Costa Jesus de Oliveira",nickname:"Caio Costa",number:"",pos:"Zagueiro",photo:""},
    {id:4,athleteId:"DaviApolinario2018",name:"Davi Apolinario Gomes Gambarini",nickname:"Davizinho",number:"",pos:"Ponta",photo:""},
    {id:5,athleteId:"DaviRamos2018",name:"Davi Edson Pontes Ramos da Silva",nickname:"Davi Silva",number:"",pos:"Volante",photo:""},
    {id:6,athleteId:"DaviLucena2018",name:"Davi Lucena Pereira da Silva",nickname:"Davizão",number:"",pos:"Atacante",photo:""},
    {id:7,athleteId:"DaviFirmiano 2018",name:"Davi Silva Firmiano",nickname:"Davi Firmiano",number:"",pos:"Meia",photo:""},
    {id:8,athleteId:"DominicCarvalho2018",name:"Dominic de Carvalho Pereira",nickname:"Dominiic Pereira",number:"",pos:"Goleiro",photo:""},
    {id:9,athleteId:"JosePedro2018",name:"José Pedro Souza da Silva",nickname:"Zezinho",number:"",pos:"Volante",photo:""},
    {id:10,athleteId:"JosephPimenta2018",name:"Joseph  Santana Pimenta",nickname:"Joseph",number:"",pos:"Volante",photo:""},
    {id:11,athleteId:"KauanGuilherme2018",name:"Kauan Guilherme Conrado Gonçalves",nickname:"Kauan Gonçalves",number:"",pos:"Volante",photo:""},
    {id:12,athleteId:"LeonardoVelardo2018",name:"Leonardo Fernandes Velardo Soares",nickname:"Leonardo Soares",number:"",pos:"Lateral Direito",photo:""},
    {id:13,athleteId:"LuccaMoutela2018",name:"Lucca Moutela Silva Mello Junior",nickname:"Lucca Moutela",number:"",pos:"Meia",photo:""},
    {id:14,athleteId:"MatheusEnrik2018",name:"Matheus Henrik de Souza Oliveira",nickname:"Matheus Henrik",number:"",pos:"Atacante",photo:""},
    {id:15,athleteId:"PedroHenrique2018",name:"Pedro Henrique da SIlva Mello Junior",nickname:"Pedrão",number:"",pos:"Volante",photo:""},
    {id:16,athleteId:"PedroLabis2018",name:"Pedro Soares Labis",nickname:"Pedrinho",number:"",pos:"Meia",photo:""},
    {id:17,athleteId:"PietroLameira2018",name:"Pietro Lameira Ferreira",nickname:"Pietro Ferreira",number:"",pos:"Meia",photo:""},
    {id:18,athleteId:"PyetroSilva2018",name:"Pyetro da Silva Moura Oliveira",nickname:"Pyetro Oliveira",number:"",pos:"Goleiro",photo:""},
    {id:19,athleteId:"RamonOliveira2018",name:"Ramon Oliveira Satyro",nickname:"Ramon Satyro",number:"",pos:"Goleiro",photo:""},
    {id:20,athleteId:"RaphaelJunior2018",name:"Raphael Junior Almeidaa Dos Santos",nickname:"Raphael Santos",number:"",pos:"Goleiro",photo:""},
    {id:21,athleteId:"ThiagoCarpi2018",name:"Thiago Lengruber Carpi",nickname:"Thiago Carpi",number:"",pos:"Volante",photo:""},
  ],
  "Sub 09": [
    {id:1,athleteId:"AntonioBrito2017",name:"Antônio Andrey Araújo de Brito",nickname:"Antônio Brito",number:"",pos:"Meia",photo:""},
    {id:2,athleteId:"ArthurAlvarez2017",name:"Arthur Alvarez Marvila",nickname:"Arthur Marvila",number:"",pos:"Ponta",photo:""},
    {id:3,athleteId:"ArthurFreesz2017",name:"Arthur de Oliveira Freesz",nickname:"Arthur Freesz",number:"",pos:"Ponta",photo:""},
    {id:4,athleteId:"ArthurRickelme2017",name:"Arthur Rickelme Euclides de Almeida Santos",nickname:"Arthur Riquelme",number:"",pos:"Meia",photo:""},
    {id:5,athleteId:"CauaPimenta2017",name:"Cauã da Silva Pimenta",nickname:"Cauã Pimenta",number:"",pos:"Goleiro",photo:""},
    {id:6,athleteId:"ChristianSantos2017",name:"Christian Oliveira Gomes dos Santos",nickname:"Christian Santos",number:"",pos:"Ponta",photo:""},
    {id:7,athleteId:"DaviSena2017",name:"Davi da Silva Sena",nickname:"Davi Sena",number:"",pos:"Zagueiro",photo:""},
    {id:8,athleteId:"DaviMoreira2017",name:"Davi Lucca da Silva Moreira",nickname:"Davi Lucca",number:"",pos:"Atacante",photo:""},
    {id:9,athleteId:"DaviGonçalves2017",name:"Davi Lukas Conrado Gonçalves",nickname:"Davi Lukas",number:"",pos:"Atacante",photo:""},
    {id:10,athleteId:"DaviFernandes2017",name:"Davi Moraes Moura Fernandes",nickname:"Davi Moraes",number:"",pos:"Meia",photo:""},
    {id:11,athleteId:"GustavoBrandao2017",name:"Gustavo de Souza Brandão",nickname:"Gustavo Brandão",number:"",pos:"Lateral Direito",photo:""},
    {id:12,athleteId:"HeitorPereira2017",name:"Heitor Luis Rodrigues Pereira",nickname:"Heitor Pereira",number:"",pos:"Meia",photo:""},
    {id:13,athleteId:"HeitorRodrigues2017",name:"Heitor Rodrigues de  Souza",nickname:"Heitor Rodrigues",number:"",pos:"Meia",photo:""},
    {id:14,athleteId:"HudsonMedina2017",name:"Hudson Ribeiro Medina",nickname:"Hudson Medina",number:"",pos:"Zagueiro",photo:""},
    {id:15,athleteId:"JonasOliveira2017",name:"Jonas de Sá Oliveira",nickname:"Jonas",number:"",pos:"Zagueiro",photo:""},
    {id:16,athleteId:"LuccaSantana2017",name:"Lucca Gabriel Oliveira Santana",nickname:"Lucca Santana",number:"",pos:"Ponta",photo:""},
    {id:17,athleteId:"LuisTavares2017",name:"Luis Felipe Medeiros Tavares",nickname:"Luis Tavares",number:"",pos:"Zagueiro",photo:""},
    {id:18,athleteId:"MateusCarvalho2017",name:"Mateus Trigueiro Mendes de Carvalho",nickname:"Mateus Carvalho",number:"",pos:"Atacante",photo:""},
    {id:19,athleteId:"NathanPaqual2017",name:"Nathan Penha Inácio Paqual",nickname:"Nathan Paqual",number:"",pos:"Atacante",photo:""},
    {id:20,athleteId:"PedroAlmeida2017",name:"Pedro Lucas Gonçalves de Almeida",nickname:"Pedro Almeida",number:"",pos:"Goleiro",photo:""},
    {id:21,athleteId:"RafaelDuarte2017",name:"Rafael Miranda Duarte",nickname:"Rafael Duarte",number:"",pos:"Goleiro",photo:""},
    {id:22,athleteId:"TheoSatiro2017",name:"Theo Vaz Lira Tolentino Satiro",nickname:"Theo Safiro",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:23,athleteId:"WillianSantos2017",name:"Willian Gabriel Fernando dos Santos",nickname:"William Santos",number:"",pos:"Ponta",photo:""},
    {id:24,athleteId:"YuriCassiano2017",name:"Yuri Gabriel Ribeiro Cassiano",nickname:"Yuri Cassiano",number:"",pos:"Meia",photo:""},
  ],
  "Sub 10": [
    {id:1,athleteId:"AntonioCalixto2016",name:"Antônio Miyao Calixto",nickname:"Antonio Calxto",number:"",pos:"Meia",photo:""},
    {id:2,athleteId:"BenjaminGarcia2016",name:"Benjamin Cunha Garcia",nickname:"Garcia",number:"",pos:"Goleiro",photo:""},
    {id:3,athleteId:"BenjaminJorge2016",name:"Benjamin Jorge da Silva Santos",nickname:"Benjamin",number:"",pos:"Goleiro",photo:""},
    {id:4,athleteId:"CaioHipolito2016",name:"Caio VInicius Hipolito de Sousa",nickname:"Caio Sousa",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:5,athleteId:"DanielPerdigo2016",name:"Daniel Perdigó Merub",nickname:"Daniel",number:"",pos:"Ponta",photo:""},
    {id:6,athleteId:"DeyvisonRodrigo2016",name:"Deyvison Rodrigo Campos Onjas de Melo",nickname:"Deyvisson Melo",number:"",pos:"Meia",photo:""},
    {id:7,athleteId:"FelipeFelizardo2016",name:"Felipe Felizardo Mourão",nickname:"Felipe Felzardo",number:"",pos:"Zagueiro",photo:""},
    {id:8,athleteId:"GabrielPotenciano2016",name:"Gabriel Potenciano Landi Cardoso",nickname:"Potenciano",number:"",pos:"Volante",photo:""},
    {id:9,athleteId:"IsaacVital2016",name:"Isaac Luiz Vital Gama da Silva",nickname:"Isaac Gama",number:"",pos:"Zagueiro",photo:""},
    {id:10,athleteId:"JoãoPedroAscari2016",name:"João Pedro Ascari Koltum",nickname:"João Pedro Ascar",number:"",pos:"Zagueiro",photo:""},
    {id:11,athleteId:"KauaLuccas2016",name:"Kauã Luccas da Silva Pereira",nickname:"Kauã Luccas",number:"",pos:"Lateral Direito",photo:""},
    {id:12,athleteId:"LucasRodrigues2016",name:"Lucas Rodrigues Barbosa da Silva",nickname:"Lucas",number:"",pos:"Lateral Direito",photo:""},
    {id:13,athleteId:"LuisEmanoel2016",name:"Luis Emanoel Farias de Carvalho",nickname:"Luis Emanoel",number:"",pos:"Ponta",photo:""},
    {id:14,athleteId:"MarceloPaulo2016",name:"Marcelo Paulo Filho",nickname:"Marcelo Paulo",number:"",pos:"Volante",photo:""},
    {id:15,athleteId:"MatheusMagaldi2016",name:"Matheus Magaldi Aide",nickname:"Aide",number:"",pos:"Atacante",photo:""},
    {id:16,athleteId:"MiguelSoubier2016",name:"Miguel  Martins Soubier",nickname:"Miguel Soubier",number:"",pos:"Atacante",photo:""},
    {id:17,athleteId:"MuriloVentura2016",name:"Murilo Ventura Silva",nickname:"Murilo Ventura",number:"",pos:"Zagueiro",photo:""},
    {id:18,athleteId:"PauloLoyo2016",name:"Pauo Vitor Loyo de Macedo",nickname:"Paulo Loyo",number:"",pos:"Goleiro",photo:""},
    {id:19,athleteId:"PedroAzer2016",name:"Pedro Uderman Azer",nickname:"Pedro Azer",number:"",pos:"Meia",photo:""},
    {id:20,athleteId:"TaylorSantos2016",name:"Taylor Santos da Silva",nickname:"Taylor Santos",number:"",pos:"Ponta",photo:""},
    {id:21,athleteId:"VictorHugo2016",name:"Victor Hugo Domingos de Souza",nickname:"Victor Hugo",number:"",pos:"Ponta",photo:""},
    {id:22,athleteId:"WelvisFranco2016",name:"Welvis Franco Silva Filho",nickname:"Welvinho",number:"",pos:"Meia",photo:""},
    {id:23,athleteId:"YuriSouza2016",name:"Yuri Pinheiro de Souza",nickname:"Yuri",number:"",pos:"Zagueiro",photo:""},
  ],
  "Sub 11": [
    {id:1,athleteId:"ArthurBastos2015",name:"Arthur de Souza Alves Bastos",nickname:"Arthur Bastos",number:"",pos:"Goleiro",photo:""},
    {id:2,athleteId:"BenicioTeles2015",name:"Benício de Oliveira Teles",nickname:"Benicio Teles",number:"",pos:"Ponta",photo:""},
    {id:3,athleteId:"BernardoCunha2015",name:"BERNARDO IVAN DA CUNHA",nickname:"Bernardo Ivan",number:"",pos:"Goleiro",photo:""},
    {id:4,athleteId:"BernardoSevero2015",name:"Bernardo Silva Severo",nickname:"Bernardo Severo",number:"",pos:"Ponta",photo:""},
    {id:5,athleteId:"CaioMaciel2015",name:"Caio Rocha Guedes Maciel",nickname:"Caio Maciel",number:"",pos:"Volante",photo:""},
    {id:6,athleteId:"EnzoReis2015",name:"Enzo Alves Cardoso Reis",nickname:"Enzo Reis",number:"",pos:"Volante",photo:""},
    {id:7,athleteId:"EnzoMendes2015",name:"Enzo Côrrea Mendes",nickname:"Enzo Mendes",number:"",pos:"Ponta",photo:""},
    {id:8,athleteId:"EnzoXavier2015",name:"Enzo Gabriel do Santos Xavier",nickname:"Enzo Xavier",number:"",pos:"Zagueiro",photo:""},
    {id:9,athleteId:"ErickSantos2015",name:"Erick de Oliveira dos Santos",nickname:"Erick Santos",number:"",pos:"Lateral Direito",photo:""},
    {id:10,athleteId:"ErickoMaia2015",name:"Ericko Rodrigo da Silva Maia",nickname:"Ericko Maia",number:"",pos:"Zagueiro",photo:""},
    {id:11,athleteId:"HenzoCalheiros2015",name:"Henzo Gabriel Silva Calheiros",nickname:"Henzo Calheiros",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:12,athleteId:"HugoBraga2015",name:"Hugo de Oliveira Braga",nickname:"Hugo Braga",number:"",pos:"Volante",photo:""},
    {id:13,athleteId:"JoaoLima2015",name:"João Gabriel dos Santos Lima",nickname:"João Lima",number:"",pos:"Atacante",photo:""},
    {id:14,athleteId:"JoaoSilva2015",name:"João Lucas Evangelista  da Silva",nickname:"Joao Silva",number:"",pos:"Ponta",photo:""},
    {id:15,athleteId:"JoaoMilitao2015",name:"João Lucas Gomes Militão",nickname:"João Militão",number:"",pos:"Meia",photo:""},
    {id:16,athleteId:"JoãoOliveira2015",name:"João Marcelo Marques de Oliveira",nickname:"João Marcelo",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:17,athleteId:"LorenzoCornel2015",name:"Lorenzo Cunha Guerra Cornel",nickname:"Lorenzo Cornel",number:"",pos:"Meia",photo:""},
    {id:18,athleteId:"LorenzoSantos2015",name:"LORENZO JESUS SANTOS",nickname:"Lorenzo Santos",number:"",pos:"Lateral Direito",photo:""},
    {id:19,athleteId:"LucasMesquita2015",name:"Lucas Leonardo S. de Mesquita",nickname:"Lucas Leonardo",number:"",pos:"Goleiro",photo:""},
    {id:20,athleteId:"LucasSantos2015",name:"Lucas Motta Santos",nickname:"Lucas Santos",number:"",pos:"Zagueiro",photo:""},
    {id:21,athleteId:"MarceloSoares2015",name:"Marcelo Eduardo Lima Soares",nickname:"Marcelo Soares",number:"",pos:"Atacante",photo:""},
    {id:22,athleteId:"MarceloNaslausky2015",name:"MARCELO ROMEIRO NASLAUSKY",nickname:"Marcelo Romeiro",number:"",pos:"Goleiro",photo:""},
    {id:23,athleteId:"PietroFreitas2015",name:"Pietro Corrêa Caifa Branco Freitas",nickname:"Pietro Freitas",number:"",pos:"Volante",photo:""},
    {id:24,athleteId:"RhaendelleyGomes2015",name:"Rhaendelley Souza Gomes",nickname:"Rhaendelley",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:25,athleteId:"VitorRocha2015",name:"Vitor Costa da Rocha",nickname:"Vitor Rocha",number:"",pos:"Meia",photo:""},
    {id:26,athleteId:"VitorAlcantara2015",name:"Vitor Ribeiro Brito de Alcântara",nickname:"Vitor Alcântara",number:"",pos:"Zagueiro",photo:""},
  ],
  "Sub 12": [
    {id:1,athleteId:"BryanSa2014",name:"BRYAN DE SÁ SOUZA",nickname:"Bryan",number:"",pos:"Ponta",photo:""},
    {id:2,athleteId:"CarlosSilva2014",name:"CARLOS LEONARDO SANTOS DA SILVA",nickname:"Carlinhos",number:"",pos:"Lateral Direito",photo:""},
    {id:3,athleteId:"DanielSilva2014",name:"Daniel Fasanella Pinheiro da Silva",nickname:"Daniel",number:"",pos:"Goleiro",photo:""},
    {id:4,athleteId:"DanteRiger2014",name:"DANTE GERLACH RIGER SILVA",nickname:"Dante",number:"",pos:"Volante",photo:""},
    {id:5,athleteId:"DaviSilva2014",name:"DAVI DE SOUZA DA SILVA",nickname:"Davizinho",number:"",pos:"Ponta",photo:""},
    {id:6,athleteId:"DiegoMaciel2014",name:"DIEGO MACIEL DE MENEZES SILVA",nickname:"Diego",number:"",pos:"Ponta",photo:""},
    {id:7,athleteId:"DiogoParente2014",name:"DIOGO PARENTE APEELBAUM",nickname:"Diogo GK",number:"",pos:"Goleiro",photo:""},
    {id:8,athleteId:"EnzoBianquini2014",name:"ENZO PHILIPE BIANQUINI RIBEIRO",nickname:"Enzo",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:9,athleteId:"FranciscoBossi2014",name:"FRANCISCO ECKEL BOSSI",nickname:"Chico",number:"",pos:"Meia",photo:""},
    {id:10,athleteId:"GabrielOrnat2014",name:"GABRIEL BENICIO ORNAT",nickname:"Gabriel Ornat",number:"",pos:"Atacante",photo:""},
    {id:11,athleteId:"GabrielSantana2014",name:"GABRIEL NASCIMENTO SANTANA",nickname:"Gabriel GK",number:"",pos:"Goleiro",photo:""},
    {id:12,athleteId:"GlauberCouto2014",name:"GLAUBER FRANCO COUTO",nickname:"Glauber",number:"",pos:"Ponta",photo:""},
    {id:13,athleteId:"GuilhermeBomfim2014",name:"GUILHERME BOMFIM CORDEIRO",nickname:"Gui Bomfim",number:"",pos:"Ponta",photo:""},
    {id:14,athleteId:"GustavoMendonca2014",name:"GUSTAVO MENDONÇA ALVES",nickname:"Gustavo",number:"",pos:"Zagueiro",photo:""},
    {id:15,athleteId:"JoaoGofferman2014",name:"João Pedro Vasconcellos Gofferman Dutra",nickname:"João Gofferman",number:"",pos:"Meia",photo:""},
    {id:16,athleteId:"JoaoHonorato2014",name:"JOÃO VITOR HONORATO BATISTA",nickname:"João Honorato",number:"",pos:"Zagueiro",photo:""},
    {id:17,athleteId:"LorenzoMaciel2014",name:"LORENZO MACIEL FARIAS",nickname:"Lorenzo GK",number:"",pos:"Goleiro",photo:""},
    {id:18,athleteId:"LucasSabatine2014",name:"LUCAS SABATINE DA SILVA",nickname:"Sabatine",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:19,athleteId:"LuizChagas2014",name:"LUIZ MIGUEL DAS CHAGAS PINTO",nickname:"Luiz Chagas",number:"",pos:"Zagueiro",photo:""},
    {id:20,athleteId:"MatheusSilva2014",name:"MATHEUS HENRIQUE SILVA",nickname:"Matheus GK",number:"",pos:"Goleiro",photo:""},
    {id:21,athleteId:"MiguelGama2014",name:"MIGUEL DO NASCIMENTO GAMA",nickname:"Miguel Gama",number:"",pos:"Lateral Direito",photo:""},
    {id:22,athleteId:"MiguelFernandes2014",name:"MIGUEL FERNANDES DA SILVA",nickname:"Miguel Fernandes",number:"",pos:"Meia",photo:""},
    {id:23,athleteId:"MuriloAroucha2014",name:"MURILO DOS SANTOS AROUCHA",nickname:"Murilo",number:"",pos:"Atacante",photo:""},
    {id:24,athleteId:"NathanAssis2014",name:"NATHAN GABRIEL SILVA DE ASSIS",nickname:"Nathan",number:"",pos:"Volante",photo:""},
    {id:25,athleteId:"RafaelAlmeida2014",name:"RAFAEL VACCHIANO ALMEIDA",nickname:"Rafael",number:"",pos:"Zagueiro",photo:""},
    {id:26,athleteId:"VicenteAzer2014",name:"VICENTE UDERMAN AZER",nickname:"Vicente",number:"",pos:"Meia",photo:""},
  ],
  "Sub 13": [
    {id:1,athleteId:"ArthurSantana2013",name:"ARTHUR SANTANA RODRIGUES FERREIRA",nickname:"Arthur Santana",number:"",pos:"Atacante",photo:""},
    {id:2,athleteId:"EnzoGabriel2013",name:"ENZO GABRIEL COSTA BARBOSA",nickname:"Enzo Gabriel",number:"",pos:"Atacante",photo:""},
    {id:3,athleteId:"ThiagoKasmirski2013",name:"THIAGO KASMIRSKI BUNO",nickname:"Thiago",number:"",pos:"Atacante",photo:""},
    {id:4,athleteId:"ArthurLeonardo2013",name:"ARTHUR LEONARDO DA SILVA RODRIGUES",nickname:"Arthur Leonardo GK",number:"",pos:"Goleiro",photo:""},
    {id:5,athleteId:"EduardoCosta2013",name:"EDUARDO COSTA MARIANTE",nickname:"Eduardo Costa GK",number:"",pos:"Goleiro",photo:""},
    {id:6,athleteId:"GuilhermeMedeiros2013",name:"GUILHERME MEDEIROS DE CASTRO RAMIRO",nickname:"Guilherme Medeiros GK",number:"",pos:"Goleiro",photo:""},
    {id:7,athleteId:"JoaoMiguel2013",name:"JOÃO MIGUEL FELIZ DA SILVA",nickname:"João Miguel",number:"",pos:"Lateral Direito",photo:""},
    {id:8,athleteId:"KayoLima2013",name:"KAYO LIMA MARCELINO DOS SANTOS",nickname:"Kayo Lima",number:"",pos:"Lateral Direito",photo:""},
    {id:9,athleteId:"EnzoClemente2013",name:"ENZO CLEMENTE TARSITANO REIS",nickname:"Enzo Clemente",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:10,athleteId:"PietroAndrey2013",name:"PIETRO ANDREY MACHADO DA SILVA",nickname:"Pietro Andrey",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:11,athleteId:"TheoDias2013",name:"THÉO DIAS SILVA",nickname:"Théo",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:12,athleteId:"BernardoAiex2013",name:"BERNARDO AIEX MENDES DE CARVALHO",nickname:"Bernardo Aiex",number:"",pos:"Meia",photo:""},
    {id:13,athleteId:"GustavoPereira2013",name:"GUSTAVO PEREIRA DA SILVA",nickname:"Gustavo Pereira",number:"",pos:"Meia",photo:""},
    {id:14,athleteId:"NikenzoSantos2013",name:"NIKENZO DA SILVA SANTOS",nickname:"Nikenzo",number:"",pos:"Meia",photo:""},
    {id:15,athleteId:"BernardoMarins2013",name:"BERNARDO MARINS ZOZIMO",nickname:"Bernardo Marins",number:"",pos:"Ponta",photo:""},
    {id:16,athleteId:"IvanLucas2013",name:"IVAN LUCAS GOMES DE OLIVEIRA",nickname:"Ivan",number:"",pos:"Ponta",photo:""},
    {id:17,athleteId:"KauanCharles2013",name:"KAUÃN CHARLES BARBOSA DA SILVA",nickname:"Kauã Charles",number:"",pos:"Ponta",photo:""},
    {id:18,athleteId:"RhayGabriel2013",name:"RHAY GABRIEL DE OLIVEIRA PAVUNA",nickname:"Rhay",number:"",pos:"Ponta",photo:""},
    {id:19,athleteId:"DaviHenrique2013",name:"DAVI HENRIQUE DIAS MARTINS RIBEIRO",nickname:"Davi Henrique",number:"",pos:"Volante",photo:""},
    {id:20,athleteId:"DiegoVelloso2013",name:"DIEGO VELLOSO DE CAMARGO",nickname:"Diego Velloso",number:"",pos:"Volante",photo:""},
    {id:21,athleteId:"MiguelVitor2013",name:"MIGUEL VITOR FERREIRA RODRIGUES",nickname:"Miguel Vitor",number:"",pos:"Volante",photo:""},
    {id:22,athleteId:"PapaDiop2014",name:"PAPA DAME DIOP",nickname:"Papa",number:"",pos:"Volante",photo:""},
    {id:23,athleteId:"PietroAragon2013",name:"PIETRO ISRAEL ARAGON DE BARROS",nickname:"Pietro Aragon",number:"",pos:"Volante",photo:""},
    {id:24,athleteId:"BentoRangel2013",name:"BENTO RANGEL DE SOUZA FERREIRA",nickname:"Bento",number:"",pos:"Zagueiro",photo:""},
    {id:25,athleteId:"BernardoPraca2013",name:"BERNARDO PRAÇA LUZIA DOS SANTOS",nickname:"Bernardo Praça",number:"",pos:"Zagueiro",photo:""},
    {id:26,athleteId:"GuilhermeCristovam2013",name:"GUILHERME DA SILVA CRISTOVAM",nickname:"Guilherme",number:"",pos:"Zagueiro",photo:""},
    {id:27,athleteId:"KaueBraga2013",name:"KAUÊ BRAGA DA SILVA PINTO",nickname:"Kauê Braga",number:"",pos:"Zagueiro",photo:""},
    {id:28,athleteId:"VitorCamelo2013",name:"VITOR CAMELO TAVARES BITENCOURT",nickname:"Vitor",number:"",pos:"Zagueiro",photo:""},
  ],
  "Sub 14": [
    {id:1,athleteId:"AlefferRodrigues2012",name:"ALEFFER PIETRO DE OLIVEIRA RODRIGUES",nickname:"ALEFFER",number:"",pos:"Atacante",photo:"https://i.imgur.com/hFYlXRxl.jpg"},
    {id:2,athleteId:"GuilhermeSouza2012",name:"GUILHERME SOUZA",nickname:"GUILHERME",number:"",pos:"Atacante",photo:""},
    {id:3,athleteId:"DaviAguiar2012",name:"DAVI LUIZ MOTA AGUIAR",nickname:"DAVI AGUIAR",number:"",pos:"Atacante",photo:""},
    {id:4,athleteId:"BrunoJubilado2012",name:"BRUNO DE SOUSA JUBILADO",nickname:"BRUNO",number:"",pos:"Goleiro",photo:"https://i.imgur.com/rtHmaFgl.jpg"},
    {id:5,athleteId:"DavidLima2012",name:"DAVID SAMUEL SOUSA ALVES DE LIMA",nickname:"DAVID",number:"",pos:"Goleiro",photo:"https://i.imgur.com/cMcJdNtl.jpg"},
    {id:6,athleteId:"LucasMachado2012",name:"LUCAS GABRIEL MACHADO",nickname:"LUCAS",number:"",pos:"Goleiro",photo:"https://i.imgur.com/RC2F26ql.jpg"},
    {id:7,athleteId:"LucasGuedes2012",name:"LUCAS BEDA INOJOSA GUEDES",nickname:"BEDA",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/pT5Pk9Nl.jpg"},
    {id:8,athleteId:"LuizCorrea2012",name:"LUIZ MIGUEL GONÇALVES XIMENES CORREA",nickname:"LUIZ MIGUEL",number:"",pos:"Lateral Direito",photo:""},
    {id:9,athleteId:"GustavoCardoso2012",name:"GUSTAVO DE OLIVEIRA CARDOSO",nickname:"GUSTAVO CARDOSO",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:10,athleteId:"JoaoSousa2012",name:"JOÃO BERTOZI OLIVIERA SOUSA",nickname:"BERTOZI",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/pqgd4CDl.jpg"},
    {id:11,athleteId:"DaviAlcantra2012",name:"DAVI MOURA CAMPOS DE ALCÂNTRA",nickname:"DAVI MOURA",number:"",pos:"Meia",photo:"https://i.imgur.com/xXSOa5cl.jpg"},
    {id:12,athleteId:"EnzoPinna2012",name:"ENZO LIMA DE PINNA",nickname:"ENZO LIMA",number:"",pos:"Meia",photo:"https://i.imgur.com/rolYxXkl.jpg"},
    {id:13,athleteId:"JoaoSilva2012",name:"JOÃO AUGUSTO LINCK DA SILVA",nickname:"LINCK",number:"",pos:"Meia",photo:"https://i.imgur.com/FNMnXiKl.jpg"},
    {id:14,athleteId:"LuizSilva2012",name:"LUIZ GUSTAVO GOMES DA SILVA",nickname:"LUIZ GUSTAVO",number:"",pos:"Meia",photo:""},
    {id:15,athleteId:"RafaelCortes2012",name:"RAFAEL LUKA KLUG CORTES",nickname:"RAFA LUKA",number:"",pos:"Meia",photo:""},
    {id:16,athleteId:"RhuanVetromila2012",name:"RHUAN SENA VETROMILA",nickname:"RHUAN",number:"",pos:"Meia",photo:"https://i.imgur.com/5yZQ2LNl.jpg"},
    {id:17,athleteId:"AdrianoEleuterio2012",name:"ADRIANO JUNIOR ELEUTÉRIO",nickname:"ADRIANO",number:"",pos:"Ponta",photo:"https://i.imgur.com/siq7zJ0l.jpg"},
    {id:18,athleteId:"BernardRodrigues2012",name:"BERNARD AMADO DE OLIVEIRA RODRIGUES",nickname:"AMADO",number:"",pos:"Ponta",photo:"https://i.imgur.com/0GXWJS8l.jpg"},
    {id:19,athleteId:"BernardoRocha2012",name:"BERNARDO VIERA DA ROCHA",nickname:"BEZINHO",number:"",pos:"Ponta",photo:"https://i.imgur.com/lr399lDl.jpg"},
    {id:20,athleteId:"YagoLourenço2012",name:"YAGO LELIS LOURENÇO",nickname:"YAGO LELIS",number:"",pos:"Ponta",photo:"https://i.imgur.com/DcEm7VPl.jpg"},
    {id:21,athleteId:"FredRaposo2012",name:"FRED DE SOUZA RAPOSO",nickname:"FRED",number:"",pos:"Volante",photo:"https://i.imgur.com/jCSBORUl.jpg"},
    {id:22,athleteId:"HenzoQuerino2012",name:"HENZO SANTANA QUERINO",nickname:"HENZO",number:"",pos:"Volante",photo:""},
    {id:23,athleteId:"DaviSoares2012",name:"DAVI DUQUE ESTRADA SANTOS SOARES",nickname:"DUQUE",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/09aj2Vnl.jpg"},
    {id:24,athleteId:"JoaoCosta2012",name:"JOÃO HENRIQUE ULIAN DA COSTA",nickname:"JOÃO HENRIQUE",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/3valr9el.jpg"},
    {id:25,athleteId:"KauaMelo2012",name:"KAUÃ DA SILVA PAULA DE MELO",nickname:"KAUÃ",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/n5M6wgrl.jpg"},
    {id:26,athleteId:"PedroSantos2012",name:"PEDRO LUCCA MENDES SANTOS",nickname:"PEDRO LUCA",number:"",pos:"Zagueiro",photo:""},
    {id:27,athleteId:"EnzoViana2012",name:"ENZO CAMPOS VIANA",nickname:"ENZO Viana",number:"",pos:"Zagueiro",photo:""},
  ],
  "Sub 15": [
    {id:1,athleteId:"AdryanGusmao2011",name:"ADRYAN NICHOLLAS DA SILVA GUSMÃO",nickname:"ADRYAN",number:"",pos:"Ponta",photo:"https://i.imgur.com/BFt7WuBl.jpg"},
    {id:2,athleteId:"ArthurBraganca2011",name:"ARTHUR CORREA MENGHINI BRAGANÇA",nickname:"ARTHUR",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/zJSK3wtl.jpg"},
    {id:3,athleteId:"BernardoAraujo2011",name:"BERNARDO DE CARVALHO ARAÚJO",nickname:"BEZINHO",number:"",pos:"Volante",photo:""},
    {id:4,athleteId:"BrayanBento2011",name:"BRAYAN BARBOSA BENTO",nickname:"BRAYAN",number:"",pos:"Meia",photo:"https://i.imgur.com/Ua3zfXel.jpg"},
    {id:5,athleteId:"CarlosGomes2011",name:"CARLOS FILLYPE SANTANA GOMES",nickname:"FILLYPE",number:"",pos:"Goleiro",photo:"https://i.imgur.com/12PoArYl.jpg"},
    {id:6,athleteId:"DaviSilva2011",name:"DAVI MACHADO DA SILVA",nickname:"DAVI MACHADO",number:"",pos:"Goleiro",photo:""},
    {id:7,athleteId:"DaviCunha2011",name:"DAVI MOURA CUNHA",nickname:"MOURA",number:"",pos:"Meia",photo:"https://i.imgur.com/ZQscZ4Il.jpg"},
    {id:8,athleteId:"DaviRodrigues2011",name:"DAVI OLIVEIRA RODRIGUES",nickname:"RODRIGUES",number:"",pos:"Volante",photo:""},
    {id:9,athleteId:"DaviOliveira2011",name:"DAVI RODRIGUES DE OLIVEIRA",nickname:"DADA",number:"",pos:"Ponta",photo:""},
    {id:10,athleteId:"DeividSouza2011",name:"DEIVID LUCAS DA CRUZ DE SOUZA",nickname:"DEIVID",number:"",pos:"Atacante",photo:""},
    {id:11,athleteId:"EnzoFerreira2011",name:"ENZO FREIRE FERREIRA",nickname:"ENZO",number:"",pos:"Goleiro",photo:"https://i.imgur.com/0OGVxZ8l.jpg"},
    {id:12,athleteId:"FabricioMerede2011",name:"FABRICIO NASCIMENTO MEREDE",nickname:"FABRICIO",number:"",pos:"Goleiro",photo:"https://i.imgur.com/pBO4nyHl.jpg"},
    {id:13,athleteId:"GustavoSantos2011",name:"GUSTAVO DE OLIVEIRA FERREIRA DOS SANTOS",nickname:"GUSTAVO",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/3zoaRJFl.jpg"},
    {id:14,athleteId:"JeanFilho2011",name:"JEAN CARLOS DA ROCHA CARVALHO FILHO",nickname:"JEAN",number:"",pos:"Atacante",photo:""},
    {id:15,athleteId:"JoaoSilva2011",name:"JOÃO VITOR WEINRICH DA SILVA",nickname:"JOÃO VITOR",number:"",pos:"Volante",photo:""},
    {id:16,athleteId:"JoseJunior2011",name:"JOSÉ MARCELO GONÇALVES NASCIMENTO JUNIOR",nickname:"JOSÉ",number:"",pos:"Meia",photo:"https://i.imgur.com/NFGfj4nl.jpg"},
    {id:17,athleteId:"KauaSouza2011",name:"KAUÃ LUCAS VITORIO SOUZA",nickname:"PAVUNA",number:"",pos:"Meia",photo:"https://i.imgur.com/mto06oNl.jpg"},
    {id:18,athleteId:"LauenderGoncalves2011",name:"LAUENDER GABRIEL SANTOS GONÇALVES",nickname:"LAUENDER",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/v3uoaqel.jpg"},
    {id:19,athleteId:"LucasGracas2011",name:"LUCAS LIMA DAS GRAÇAS",nickname:"MACUCO",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/3Gh6w67l.jpg"},
    {id:20,athleteId:"MatheusSilva2011",name:"MATHEUS EDUARDO ALVES DA SILVA",nickname:"MATHEUS",number:"",pos:"Ponta",photo:"https://i.imgur.com/JuXXpBrl.jpg"},
    {id:21,athleteId:"PauloRodrigues2011",name:"PAULO CÉZAR FILHO BOAVENTURA RODRIGUES",nickname:"PAULINHO",number:"",pos:"Ponta",photo:"https://i.imgur.com/uNLJSU0l.jpg"},
    {id:22,athleteId:"PedroPinheiro2011",name:"PEDRO HENRIQUE DE SÁ PINHEIRO",nickname:"CDD",number:"",pos:"Ponta",photo:"https://i.imgur.com/Swzh8Fwl.jpg"},
    {id:23,athleteId:"ValmirGramelik2011",name:"VALMIR RIBEIRO GRAMELIK",nickname:"VALMIR",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/qOapNtgl.jpg"},
    {id:24,athleteId:"VictorSilva2011",name:"VICTOR HUGO GOUVEIA DA SILVA",nickname:"VICTOR HUGO",number:"",pos:"Volante",photo:"https://i.imgur.com/8SmqByol.jpg"},
    {id:25,athleteId:"ViniciusMalaquias2011",name:"VINÍCIUS ALVES MALAQUIAS",nickname:"MALAQUIAS",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/AvvHWGBl.jpg"},
    {id:26,athleteId:"WandslanMoraes2011",name:"WANDSLAN VALERIO DOS SANTOS MORAES",nickname:"MORAES",number:"",pos:"Ponta",photo:""},
  ],
  "Sub 16": [
    {id:1,athleteId:"AlessandroDantas2010",name:"ALESSANDRO ALAN FERREIRA DANTAS",nickname:"ALESSANDRO DANTAS",number:"",pos:"Goleiro",photo:"https://i.imgur.com/tJZXD0il.jpg"},
    {id:2,athleteId:"FabioCastro2010",name:"FABIO HENRIQUE LABADESSA DE CASTRO",nickname:"FÁBIO",number:"",pos:"Meia",photo:""},
    {id:3,athleteId:"FelipeClemente2010",name:"FELIPE PINA FERREIRA CLEMENTE",nickname:"FELIPE PINA",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/oJHe7bml.jpg"},
    {id:4,athleteId:"GuilhermeSouza2010",name:"GUILHERME MATHEUS CEZARIO DE SOUZA",nickname:"GUILHERME MATHEUS",number:"",pos:"Zagueiro",photo:""},
    {id:5,athleteId:"HenriqueManrich2010",name:"HENRIQUE MANNRICH",nickname:"Henrique Mannrich",number:"",pos:"Volante",photo:""},
    {id:6,athleteId:"JoseSouza2010",name:"JOSÉ EDUARDO DOS SANTOS DE SOUZA",nickname:"JOSÉ EDUARDO",number:"",pos:"Ponta",photo:"https://i.imgur.com/jVHfdN8l.jpg"},
    {id:7,athleteId:"KlismannSilva2010",name:"KLISMANN SOTELLE SILVA",nickname:"KLISMANN SILVA",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/1Vx0N6al.jpg"},
    {id:8,athleteId:"LeandroMatos2010",name:"LEANDRO GUSTAVO MATOS",nickname:"LEANDRO GUSTAVO",number:"",pos:"Atacante",photo:""},
    {id:9,athleteId:"LucasGuedes2010",name:"LUCAS DE ARAUJO DA SILVA GUEDES",nickname:"LUCAS GUEDES",number:"",pos:"Volante",photo:""},
    {id:10,athleteId:"MarceloPret2010",name:"MARCELO PORTELA PARADA DE PRET",nickname:"MARCELO",number:"",pos:"Ponta",photo:""},
    {id:11,athleteId:"MarcosFernandes2010",name:"MARCOS PIERRE SANTOS FERNANDES",nickname:"MARCOS PIERRE",number:"",pos:"Ponta",photo:"https://i.imgur.com/HQpseAZl.jpg"},
    {id:12,athleteId:"MateusSilva2010",name:"MATEUS TEIXEIRA DA SILVA",nickname:"MATEUS TEIXEIRA",number:"",pos:"Meia",photo:"https://i.imgur.com/ljxFB04l.jpg"},
    {id:13,athleteId:"NicolasFelber2010",name:"NICOLAS KISCHNER FELBER",nickname:"NICOLAS",number:"",pos:"Goleiro",photo:""},
    {id:14,athleteId:"NoahSilva2010",name:"NOAH GERLACH RIGER SILVA",nickname:"NOAH GERLACH",number:"",pos:"Volante",photo:"https://i.imgur.com/hLDSItAl.jpg"},
    {id:15,athleteId:"RafaelSouza2010",name:"RAFAEL BARRETO OLIVEIRA DE SOUZA",nickname:"RAFAEL SOUZA",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/kyP8Ocxl.jpg"},
    {id:16,athleteId:"RafaelMoraes2010",name:"RAFAEL MORAES DA COSTA JUNIOR",nickname:"RAFAEL MORAES",number:"",pos:"Lateral Direito",photo:""},
    {id:17,athleteId:"RhuanSouza2010",name:"RHUAN BATISTA DE SOUZA",nickname:"RHUAN SOUZA",number:"",pos:"Meia",photo:""},
    {id:18,athleteId:"RicardoBarbosa2010",name:"RICARDO PIETRO BARBOSA",nickname:"RICARDO BARBOSA",number:"",pos:"Lateral Direito",photo:""},
    {id:19,athleteId:"RyanAlmeida2010",name:"RYAN CARVALHO DE ALMEIDA",nickname:"RYAN ALMEIDA",number:"",pos:"Lateral Direito",photo:""},
    {id:20,athleteId:"SamuelBarbosa2010",name:"SAMUEL JÚLIO FARIA BARBOSA",nickname:"SAMUEL BARBOSA",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/nB208e8l.jpg"},
    {id:21,athleteId:"ThauanMello2010",name:"THAUAN THIAGO CERQUEIRA DE MELLO",nickname:"THAUAN MELLO",number:"",pos:"Volante",photo:"https://i.imgur.com/xdwOlj2l.jpg"},
    {id:22,athleteId:"ThomasBucard2010",name:"THOMAS ROBSON CARDOSO BUÇARD",nickname:"THOMAS BUCARD",number:"",pos:"Meia",photo:"https://i.imgur.com/jybvShvl.jpg"},
    {id:23,athleteId:"WilliamNascimento2010",name:"WILLIAN FELIX NASCIMENTO",nickname:"WILLIAN FELIX",number:"",pos:"Ponta",photo:"https://i.imgur.com/YDtbtKWl.jpg"},
  ],
  "Sub 17": [
    {id:1,athleteId:"AmilcaFilho2009",name:"AMILCA SANTOS DE MELO FILHO",nickname:"AMILCA SANTOS",number:"",pos:"Atacante",photo:""},
    {id:2,athleteId:"AnthonyMucury2009",name:"ANTHONY DE AVELAR MUCURY",nickname:"ANTHONY MUCURY",number:"",pos:"Atacante",photo:"https://i.imgur.com/aXD1ws2l.jpg"},
    {id:3,athleteId:"ArthurAndrades2009",name:"ARTHUR ABRAÃO MEDEIROS DE ANDRADES",nickname:"ANDRADES",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/U6Soq93l.jpg"},
    {id:4,athleteId:"BernardoNunes2009",name:"BERNARDO DA COSTA NUNES",nickname:"BERNARDO NUNES",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/kyqI4D4l.jpg"},
    {id:5,athleteId:"BrunoSilva2009",name:"BRUNO EMANOEL AUGUSTO AUGUSTO DA SILVA",nickname:"BRUNO EMANOEL",number:"",pos:"Goleiro",photo:"https://i.imgur.com/iZsJE0Nl.jpg"},
    {id:6,athleteId:"DaviCarrijo2009",name:"DAVI CARRIJO HELRIGHEL",nickname:"Davi Carrijo",number:"",pos:"Meia",photo:""},
    {id:7,athleteId:"DaviBorges2010",name:"DAVI FRAGA BORGES",nickname:"DAVI FRAGA",number:"",pos:"Meia",photo:"https://i.imgur.com/PSjlZR9l.jpg"},
    {id:8,athleteId:"EmanuelOliveira2009",name:"EMANUEL SILVA DE OLIVEIRA",nickname:"EMANUEL",number:"",pos:"Atacante",photo:"https://i.imgur.com/wrwWku5l.jpg"},
    {id:9,athleteId:"EnricoPereira2009",name:"ENRICO MONTECHESSI PEREIRA",nickname:"ENRICO MONTECHESSI",number:"",pos:"Meia",photo:"https://i.imgur.com/qMfdVYql.jpg"},
    {id:10,athleteId:"GabrielRodrigues2009",name:"GABRIEL SANTOS LIMA MORAES RODRIGUES",nickname:"GABRIEL SANTOS",number:"",pos:"Volante",photo:"https://i.imgur.com/J9jJDj1l.jpg"},
    {id:11,athleteId:"GuilhermeQueiroz2010",name:"GUILHERME DA CRUZ OLIVEIRA QUEIROZ",nickname:"GUILHERME QUEIROZ",number:"",pos:"Atacante",photo:"https://i.imgur.com/ljxFB04l.jpg"},
    {id:12,athleteId:"GuilhermeIvo2009",name:"GUILHERME HENRIQUE MORAES IVO",nickname:"GUILHERME IVO",number:"",pos:"Meia",photo:"https://i.imgur.com/H31m6iSl.jpg"},
    {id:13,athleteId:"HeitorGabrielli2009",name:"HEITOR GABRIELLI VITORIA",nickname:"HEITOR GABRIELLI",number:"",pos:"Volante",photo:""},
    {id:14,athleteId:"IsaacSilva2009",name:"ISAAC GOMES RODRIGUES DA SILVA",nickname:"ISAAC",number:"",pos:"Ponta",photo:""},
    {id:15,athleteId:"JoaoHenrique2009",name:"JOÃO HENRIQUE BARROSO DA NOBREGA",nickname:"JOAO HENRIQUE",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/JOofTCrl.jpg"},
    {id:16,athleteId:"JordanOliveira2009",name:"JORDAN MICHAEL DE OLIVEIRA",nickname:"JORDAN OLIVEIRA",number:"",pos:"Meia",photo:""},
    {id:17,athleteId:"JulioBarroso2009",name:"Júlio César de Almeida Barroso",nickname:"JULIO CESAR",number:"",pos:"Atacante",photo:""},
    {id:18,athleteId:"KauaAlmeida2009",name:"KAUÃ CARLOS DE ALMEIDA",nickname:"KAUA",number:"",pos:"Volante",photo:"https://i.imgur.com/ffSwnHxl.jpg"},
    {id:19,athleteId:"LuccaTatsch2010",name:"LUCCA SOARES TATSCH",nickname:"LUCCA TATSCH",number:"",pos:"Volante",photo:"https://i.imgur.com/vp9JhZwl.jpg"},
    {id:20,athleteId:"LuizSantos2009",name:"LUIZ GUILHERME DA SILVA SANTOS",nickname:"LUIZ GUILHERME",number:"",pos:"Atacante",photo:"https://i.imgur.com/p0c8svzl.jpg"},
    {id:21,athleteId:"NathanRibeiro2010",name:"NATHAN DO VALE RIBEIRO",nickname:"NATHAN RIBEIRO",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/RfQ7cvvl.jpg"},
    {id:22,athleteId:"PauloCesar2009",name:"PAULO CESAR AGUIAR DA SILVA",nickname:"Paulo Cesar",number:"",pos:"Zagueiro",photo:""},
    {id:23,athleteId:"PedroPinto2009",name:"PEDRO HENRIQUE FERREIRA PINTO",nickname:"PEDRO HENRIQUE FERREIRA",number:"",pos:"Ponta",photo:"https://i.imgur.com/l1MkuSEl.jpg"},
    {id:24,athleteId:"PedroEiras2009",name:"PEDRO PINHO EIRAS",nickname:"PEDRO PINHO",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/HQ8MdbYl.jpg"},
    {id:25,athleteId:"RafaelGuerra2009",name:"RAFAEL TENÓRIO GUERRA",nickname:"RAFAEL TENORIO",number:"",pos:"Meia",photo:"https://i.imgur.com/ZdCgvDGl.jpg"},
    {id:26,athleteId:"RaymundoYkaro2009",name:"RAYMUNDO YKARO SANTOS SILVA",nickname:"RAYMUNDO YKARO",number:"",pos:"Volante",photo:""},
    {id:27,athleteId:"RuanAndrade2009",name:"RUAN MATEUS BARRETO DE ANDRADE",nickname:"RUAN",number:"",pos:"Volante",photo:""},
    {id:28,athleteId:"SamuelBaptista2009",name:"SAMUEL BAPTISTA DA SILVA",nickname:"SAMUEL BAPTISTA",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:29,athleteId:"ViniciusVieira2009",name:"VINÍCIUS ESPÍRITO SANTO VIEIRA",nickname:"VINICIUS ESPIRITO",number:"",pos:"Goleiro",photo:"https://i.imgur.com/FMN2NfXl.jpg"},
    {id:30,athleteId:"WalaceAndrade2009",name:"WALACE INACIO SANTANA DA SILVA ANDRADE",nickname:"WALLCE INACIO",number:"",pos:"Atacante",photo:""},
  ],
  "Sub 20": [
    {id:1,athleteId:"AlanSantos2007",name:"ALAN DA SILVA SANTOS",nickname:"ALAN SANTOS",number:"",pos:"Ponta",photo:"https://i.imgur.com/LR6Weykl.jpg"},
    {id:2,athleteId:"AntonioGermano2006",name:"ANTONIO GERMANO DA SILVA NETO",nickname:"ANTONIO GERMANO",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/uyqsQzAl.jpg"},
    {id:3,athleteId:"CaioJoshua2007",name:"CAIO JOSHUA LANA DE ANDRADE",nickname:"CAIO JOSHUA",number:"",pos:"Meia",photo:"https://i.imgur.com/x4x9cF2l.jpg"},
    {id:4,athleteId:"DanielMarinho2009",name:"DANIEL CARVALHO MARINHO DA SILVA",nickname:"DANIEL CARVALHO",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/aDLtesYl.jpg"},
    {id:5,athleteId:"DanielSales2006",name:"DANIEL DOS SANTOS SALES",nickname:"DANIEL SALES",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/VeAJtAHl.jpg"},
    {id:6,athleteId:"DaviWaisman2008",name:"DAVI MILHOMENS WAISMAN",nickname:"DAVI WAISMAN",number:"",pos:"Ponta",photo:"https://i.imgur.com/EC2bQnRl.jpg"},
    {id:7,athleteId:"DavidViana2007",name:"DAVID VIANA DE OLIVEIRA",nickname:"DAVID VIANA",number:"",pos:"Meia",photo:"https://i.imgur.com/Gfrcsikl.jpg"},
    {id:8,athleteId:"DiegoNeves2008",name:"DIEGO GUIMARAES DAS NEVES",nickname:"DIEGO NEVES",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/pn7dNaxl.jpg"},
    {id:9,athleteId:"DouglasTelles2007",name:"DOUGLAS COSTA TELES",nickname:"DOUGLAS TELLES",number:"",pos:"Ponta",photo:"https://i.imgur.com/VlW5ly9l.jpg"},
    {id:10,athleteId:"EduardoClasen2008",name:"EDUARDO LUIS CLASEN",nickname:"EDUARDO CLASEN",number:"",pos:"Goleiro",photo:"https://i.imgur.com/Gqe2IAzl.jpg"},
    {id:11,athleteId:"EnzoBernabe2008",name:"ENZO PINHEIRO BARNABE",nickname:"ENZO PINHEIRO",number:"",pos:"Volante",photo:"https://i.imgur.com/bdTafoul.jpg"},
    {id:12,athleteId:"ErnestMellis2006",name:"Ernest Muñoz Mellis",nickname:"Muñoz",number:"",pos:"Zagueiro",photo:""},
    {id:13,athleteId:"FabioRibeiro2006",name:"FABIO RIBEIRO IZAIAS BALDUINO JUNIOR",nickname:"BILL RIBEIRO",number:"",pos:"Ponta",photo:"https://i.imgur.com/hPn9cmFl.jpg"},
    {id:14,athleteId:"GabrielGoncalves2008",name:"GABRIEL AMANCIO GONCALVES",nickname:"GABRIEL AMANCIO",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/vRLXqYcl.jpg"},
    {id:15,athleteId:"GabrielWerneck2009",name:"GABRIEL LAIZO WERNECK",nickname:"WERNECK",number:"",pos:"Goleiro",photo:"https://i.imgur.com/Xq7pPN6l.jpg"},
    {id:16,athleteId:"GuilhermeHenrique2006",name:"GUILHERME HENRIQUE BERNARDINELI GOMES",nickname:"GUILHERME HENRIQUE",number:"",pos:"Meia",photo:"https://i.imgur.com/sSAGq8Nl.jpg"},
    {id:17,athleteId:"GuilhermeBarbosa2007",name:"Guilherme Santos Barbosa",nickname:"GUILHERME BARBOSA",number:"",pos:"Meia",photo:"https://i.imgur.com/IlB9xvXl.jpg"},
    {id:18,athleteId:"GustavoNunes2006",name:"Gustavo Rodrigues Nunes",nickname:"Ramires",number:"",pos:"Lateral Esquerdo",photo:""},
    {id:19,athleteId:"GusttavoOliveira2006",name:"GUSTTAVO DE SOUSA OLIVEIRA",nickname:"GUSTTAVO DE SOUSA",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/DJjT4wkl.jpg"},
    {id:20,athleteId:"ItaloPereira2007",name:"ITALO PEREIRA DOS SANTOS",nickname:"ITALO PEREIRA",number:"",pos:"Lateral Esquerdo",photo:"https://i.imgur.com/AQVKzp9l.jpg"},
    {id:21,athleteId:"JhefersonRufino2008",name:"JHEFERSON VINICIUS MEDINO RUFINO",nickname:"JHEFERSON RUFINO",number:"",pos:"Meia",photo:"https://i.imgur.com/E7chZbUl.jpg"},
    {id:22,athleteId:"JoaoReis2008",name:"JOÃO CARLOS DE ANDRADE REIS",nickname:"Joao Carlos",number:"",pos:"Ponta",photo:""},
    {id:23,athleteId:"JoaoCamargo2007",name:"JOAO PAULO CAMARGO DE BARROS",nickname:"CAMARGO",number:"",pos:"Atacante",photo:"https://i.imgur.com/15z9Yzcl.jpg"},
    {id:24,athleteId:"JoaodaMata2006",name:"JOAO PEDRO DA MATA",nickname:"DA MATA",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/rJA3sNel.jpg"},
    {id:25,athleteId:"JoaoSilva2008",name:"JOÃO VICTOR COSTA PEREIRA DA SILVA",nickname:"Joao Silva",number:"",pos:"Goleiro",photo:""},
    {id:26,athleteId:"JoaoVictor2007",name:"JOAO VICTOR DE SOUZA CUNHA",nickname:"JOAO VICTOR",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/YCYlalyl.jpg"},
    {id:27,athleteId:"JoaoLauredo2009",name:"JOÃO VITOR ANDRADE COUTO LAUREDO",nickname:"JOAO VITOR",number:"",pos:"Ponta",photo:"https://i.imgur.com/KqVQTz6l.jpg"},
    {id:28,athleteId:"JohnnyGoes2007",name:"JOHNNY MONTEIRO GOES",nickname:"JOHNNY GOES",number:"",pos:"Zagueiro",photo:"https://i.imgur.com/NkmYls4l.jpg"},
    {id:29,athleteId:"JosmarMiranda2008",name:"Josmar Silva Miranda",nickname:"Josmar",number:"",pos:"Atacante",photo:""},
    {id:30,athleteId:"KaioLopes2007",name:"Kaio Júnior Camargo da Silva Lopes",nickname:"KAIO LOPES",number:"",pos:"Volante",photo:"https://i.imgur.com/LIgtByEl.jpg"},
    {id:31,athleteId:"KaioNobrega2007",name:"KAIO NOBREGA SIQUEIRA",nickname:"KAIO NOBREGA",number:"",pos:"Volante",photo:"https://i.imgur.com/yJoOqz2l.jpg"},
    {id:32,athleteId:"LeonardoNannetti2007",name:"LEONARDO NANNETTI LOPES",nickname:"LEO",number:"",pos:"Goleiro",photo:"https://i.imgur.com/u33Yldol.jpg"},
    {id:33,athleteId:"LucasLocio2008",name:"LUCAS FALCONE LOCIO",nickname:"LUCAS FALCONE",number:"",pos:"Volante",photo:"https://i.imgur.com/SbxPpQOl.jpg"},
    {id:34,athleteId:"LucasVieira2007",name:"LUCAS VIEIRA DOS SANTOS",nickname:"LUCAS VIEIRA",number:"",pos:"Volante",photo:"https://i.imgur.com/uQOVotOl.jpg"},
    {id:35,athleteId:"LuizSantos2008",name:"LUIZ FELIPE MARIANO DOS SANTOS",nickname:"LUIZ FELIPE MARIANO",number:"",pos:"Volante",photo:"https://i.imgur.com/CLGiIkkl.jpg"},
    {id:36,athleteId:"MatheusAguiar2008",name:"MATHEUS THIAGO MENDES AGUIAR",nickname:"MATHEUS THIAGO",number:"",pos:"Volante",photo:"https://i.imgur.com/O0rPDK3l.jpg"},
    {id:37,athleteId:"PabloLucio2007",name:"PABLO LUCIO",nickname:"PABLO LUCIO",number:"",pos:"Volante",photo:"https://i.imgur.com/zPg6S7Xl.jpg"},
    {id:38,athleteId:"PedroBatista2008",name:"PEDRO HENRIQUE VIEIRA BATISTA",nickname:"Pedro Henrique",number:"",pos:"Goleiro",photo:""},
    {id:39,athleteId:"RafaelSilva2008",name:"RAFAEL HENRIQUE TOMAZ DA SILVA",nickname:"RAFAEL HENRIQUE",number:"",pos:"Meia",photo:"https://i.imgur.com/FRMXX2Rl.jpg"},
    {id:40,athleteId:"RogerioJunior2008",name:"ROGERIO ARAUJO SILVA JUNIOR",nickname:"ROGERIO JUNIOR",number:"",pos:"Volante",photo:"https://i.imgur.com/dQi18Tgl.jpg"},
    {id:41,athleteId:"RyanDantas2008",name:"RYAN ROBERTO DE OLIVEIRA DANTAS",nickname:"RYAN ROBERTO",number:"",pos:"Ponta",photo:"https://i.imgur.com/Qerjjzcl.jpg"},
    {id:42,athleteId:"VictorAmaral2008",name:"VICTOR HUGO CORREIA DE AZEVEDO AMARAL",nickname:"VICTOR HUGO",number:"",pos:"Atacante",photo:"https://i.imgur.com/WzOHJzHl.jpg"},
    {id:43,athleteId:"WandersonSouza2007",name:"WANDERSON JUNIOR DE SOUZA VAZ",nickname:"WANDERSON JUNIOR",number:"",pos:"Lateral Direito",photo:"https://i.imgur.com/C2YGFYhl.jpg"},
  ],
  "Profissional": [
  ],
  "Feminino": [
  ],
};

CAT_LIST.forEach(k => { if (!SQUADS[k]) SQUADS[k] = []; });

export const DEFAULT_FORMATION = [
  {id:"p0",isGK:true,x:12,y:50},
  {id:"p1",isGK:false,x:30,y:15},
  {id:"p2",isGK:false,x:28,y:38},
  {id:"p3",isGK:false,x:28,y:62},
  {id:"p4",isGK:false,x:30,y:85},
  {id:"p5",isGK:false,x:50,y:25},
  {id:"p6",isGK:false,x:52,y:50},
  {id:"p7",isGK:false,x:50,y:75},
  {id:"p8",isGK:false,x:78,y:15},
  {id:"p9",isGK:false,x:82,y:50},
  {id:"p10",isGK:false,x:78,y:85},
];